documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#

functions:
  - my-own-equal-func
  - deep-equal

rules:
  # MUST use semantic versioning [116]
  # => https://opensource.zalando.com/restful-api-guidelines/#116

  must-use-semantic-versioning:
    message: '{{error}}'
    description: MUST use semantic versioning [116]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#116
    severity: error
    given: $.info.version
    then:
      function: schema
      functionOptions:
        schema:
          type: string
          pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'

  # MUST property names must be ASCII snake_case [118]
  # => https://opensource.zalando.com/restful-api-guidelines/#118

  must-use-snake-case-for-property-names:
    message: Property name has to be ASCII snake_case
    description: MUST property names must be ASCII snake_case [118]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#118
    severity: error
    given: $.paths.*.*.responses.*.content..schema..properties.*~
    then:
      function: pattern
      functionOptions:
        match: ^[a-z_][a-z_0-9]*$

  # MUST provide API identifiers [215]
  # => https://opensource.zalando.com/restful-api-guidelines/#215

  must-provide-api-identifiers:
    message: '{{error}}'
    description: MUST provide API identifiers [215]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#215
    severity: error
    given: $.info.x-api-id
    then:
      function: schema
      functionOptions:
        schema:
          type: string
          pattern: ^[a-z0-9][a-z0-9-:.]{6,62}[a-z0-9]$

  # MUST contain API meta information [218]
  # https://opensource.zalando.com/restful-api-guidelines/#218

  must-have-info:
    message: OpenAPI `info` must be present and an object.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $
    then:
      field: info
      function: schema
      functionOptions:
        schema:
          type: object

  must-have-info-title:
    message: Missing `info.title`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: title
      function: truthy

  must-have-info-version:
    message: Missing `info.version`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: version
      function: truthy

  must-have-info-description:
    message: Missing `info.description`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: description
      function: truthy

  must-have-info-contact-name:
    message: Missing `info.contact.name`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact.name
      function: truthy

  must-have-info-contact-url:
    message: Missing `info.contact.url`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact.url
      function: truthy

  must-have-info-contact-email:
    message: Missing `info.contact.email`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact.email
      function: truthy

  must-have-info-x-api-id:
    message: Missing `info.x-api-id`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: x-api-id
      function: truthy

  must-have-info-x-audience:
    message: Missing `info.x-audience`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: x-audience
      function: truthy