documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#

functions:
  - is-object-schema

rules:
  # MUST always return JSON objects as top-level data structures [110]
  # => https://opensource.zalando.com/restful-api-guidelines/#110

  must-always-return-json-objects-as-top-level-data-structures:
    message: 'Top-level data structure must be an object'
    description: MUST always return JSON objects as top-level data structures [110]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#110
    severity: error
    given: $.paths.*.*[responses,requestBody]..content..schema
    then:
      function: is-object-schema

  # SHOULD used open-ended list of values (x-extensible-enum) for enumerations [112]
  # => https://opensource.zalando.com/restful-api-guidelines/#112

  should-use-x-extensible-enum:
    message: 'Should use `x-extensible-enum` instead of `enum`'
    description: SHOULD used open-ended list of values (x-extensible-enum) for enumerations [112]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#112
    severity: warn
    given: $.paths..[?(@.type=='string')].enum
    then:
      function: undefined
    
  # MUST not use URI versioning [115]
  # => https://opensource.zalando.com/restful-api-guidelines/#115

  must-not-use-uri-versioning:
    message: Path must not contain versioning
    description: MUST not use URI versioning [115]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#115
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        notMatch: /v[0-9]+/

  # MUST use semantic versioning [116]
  # => https://opensource.zalando.com/restful-api-guidelines/#116

  must-use-semantic-versioning:
    message: '{{error}}'
    description: MUST use semantic versioning [116]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#116
    severity: error
    given: $.info.version
    then:
      function: schema
      functionOptions:
        schema:
          type: string
          pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'

  # MUST property names must be ASCII snake_case [118]
  # => https://opensource.zalando.com/restful-api-guidelines/#118

  must-use-snake-case-for-property-names:
    message: Property name has to be ASCII snake_case
    description: MUST property names must be ASCII snake_case [118]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#118
    severity: error
    given: $.paths.*.*[responses,requestBody]..content..schema..properties.*~
    then:
      function: pattern
      functionOptions:
        match: ^[a-z_][a-z_0-9]*$

  # MUST use lowercase separate words with hyphens for path segments [129]
  # => https://opensource.zalando.com/restful-api-guidelines/#129

  must-use-lowercase-with-hypens-for-path-segements:
    message: Path segments have to be lowercase separate words with hyphens
    description: MUST use lowercase separate words with hyphens for path segments [129]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#129
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        match: ^(([\/a-z][a-z0-9\-\/]*)?({[^}]*})?)+$

  # MUST use snake_case (never camelCase) for query parameters [130]
  # => https://opensource.zalando.com/restful-api-guidelines/#130

  must-use-snake-case-for-query-parameters:
    message: Query parameters must be snake_case
    description: MUST use snake_case (never camelCase) for query parameters [130]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#130
    severity: error
    given: $.paths.*.*.parameters[?(@.in=='query')].name
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][_a-z0-9]*$

  # SHOULD prefer hyphenated-pascal-case for HTTP header fields [132]
  # => https://opensource.zalando.com/restful-api-guidelines/#132

  should-use-hyphenated-pascal-case-for-header-parameters:
    message: Header parameters should be Hyphenated-Pascal-Case
    description: SHOULD prefer hyphenated-pascal-case for HTTP header fields [132]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#132
    severity: warn
    given: $.paths.*.*.parameters[?(@.in=='header')].name
    then:
      function: pattern
      functionOptions:
        match: ^([A-Z][a-z]*)(-[A-Z0-9][a-z0-9]*)*$

  # SHOULD not use /api as base path [135]
  # => https://opensource.zalando.com/restful-api-guidelines/#135

  should-not-use-api-as-base-path:
    message: Path should not start with /api
    description: SHOULD not use /api as base path [135]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#135
    severity: warn
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        notMatch: ^/api

  # MUST use normalized paths without empty path segments and trailing slashes [136]
  # => https://opensource.zalando.com/restful-api-guidelines/#136

  must-use-normalized-paths-without-empty-path-segments:
    message: Empty path segments are not allowed
    description: MUST use normalized paths without empty path segments and trailing slashes [136]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#136
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        notMatch: //

  must-use-normalized-paths-without-trailing-slash:
    message: Path with trailing slash is not allowed
    description: MUST use normalized paths without empty path segments and trailing slashes [136]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#136
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        notMatch: /$

  must-use-normalized-paths-with-leading-slash:
    message: Path must start with slash
    description: MUST use normalized paths without empty path segments and trailing slashes [136]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#136
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        match: ^/

  # MUST provide API identifiers [215]
  # => https://opensource.zalando.com/restful-api-guidelines/#215

  must-provide-api-identifiers:
    message: '{{error}}'
    description: MUST provide API identifiers [215]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#215
    severity: error
    given: $.info.x-api-id
    then:
      function: schema
      functionOptions:
        schema:
          type: string
          pattern: ^[a-z0-9][a-z0-9-:.]{6,62}[a-z0-9]$

  # MUST contain API meta information [218]
  # https://opensource.zalando.com/restful-api-guidelines/#218

  must-have-info:
    message: OpenAPI `info` must be present and an object.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $
    then:
      field: info
      function: schema
      functionOptions:
        schema:
          type: object

  must-have-info-title:
    message: Missing `info.title`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: title
      function: truthy

  must-have-info-version:
    message: Missing `info.version`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: version
      function: truthy

  must-have-info-description:
    message: Missing `info.description`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: description
      function: truthy

  must-have-info-contact-name:
    message: Missing `info.contact.name`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact.name
      function: truthy

  must-have-info-contact-url:
    message: Missing `info.contact.url`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact.url
      function: truthy

  must-have-info-contact-email:
    message: Missing `info.contact.email`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact.email
      function: truthy

  must-have-info-x-api-id:
    message: Missing `info.x-api-id`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: x-api-id
      function: truthy

  must-have-info-x-audience:
    message: Missing `info.x-audience`.
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: x-audience
      function: truthy

  # SHOULD declare enum values using UPPER_SNAKE_CASE format [240]
  # => https://opensource.zalando.com/restful-api-guidelines/#240

  should-declare-enum-values-using-upper-snake-case-format:
    message: 'Enum values should be in UPPER_SNAKE_CASE format'
    description: SHOULD declare enum values using UPPER_SNAKE_CASE format [240]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#240
    severity: warn
    given: $.paths..[?(@.type=='string')].[enum,x-extensible-enum].*
    then:
      function: pattern
      functionOptions:
        match: ^[A-Z][A-Z_0-9]*$
