documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#

functions:
  - my-own-equal-func
  - deep-equal

rules:
  # 4. Meta information
  # => https://opensource.zalando.com/restful-api-guidelines/#meta-information

  # MUST contain API meta information [218]
  # => https://opensource.zalando.com/restful-api-guidelines/#218

  must-have-info:
    message: Missing `#/info`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $
    then:
      field: info
      function: truthy

  must-have-info-title:
    message: Missing `#/info/title`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: title
      function: truthy

  must-have-info-version:
    message: Missing `#/info/version`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: version
      function: truthy

  must-have-info-description:
    message: Missing `#/info/description`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: description
      function: truthy

  must-have-info-contact:
    message: Missing `#/info/contact`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: contact
      function: truthy

  must-have-info-contact-name:
    message: Missing `#/info/contact/name`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info.contact
    then:
      field: name
      function: truthy

  must-have-info-contact-url:
    message: Missing `#/info/contact/url`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info.contact
    then:
      field: url
      function: truthy

  must-have-info-contact-email:
    message: Missing `#/info/contact/email`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info.contact
    then:
      field: email
      function: truthy

  must-have-info-x-api-id:
    message: Missing `#/info/x-api-id`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: x-api-id
      function: truthy

  must-have-info-x-audience:
    message: Missing `#/info/x-audience`
    description: MUST contain API meta information [218]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#218
    severity: error
    given: $.info
    then:
      field: x-audience
      function: truthy

  # MUST use semantic versioning [116]
  # => https://opensource.zalando.com/restful-api-guidelines/#116

  must-use-semantic-versioning:
    message: Value `#/info/version` {{error}}
    description: MUST use semantic versioning [116]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#116
    severity: error
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: '^[0-9]+\.[0-9]+\.[0-9]+$'

  # MUST provide API identifiers [215]
  # => https://opensource.zalando.com/restful-api-guidelines/#215

  must-provide-api-identifiers:
    message: Value `#/info/x-api-id` {{error}}
    description: MUST provide API identifiers [215]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#215
    severity: error
    given: $.info.x-api-id
    then:
      function: pattern
      functionOptions:
        match: ^[a-z0-9][a-z0-9-:.]{6,62}[a-z0-9]$

