apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: lz.chist.example # This is the name of the topic
  labels:
    strimzi.io/cluster: foo #{{ .Values.global.clusterName }}
    baloise/owned-by: B099999 # The B-Key of the data owner which approves KafkaUsers
spec:
  partitions: 1 # Change this if you scale one consumer horizontally
  replicas: 3 # As we have three brokers it makes sense to have 3
  config:
    min.insync.replicas: 2 # Makes sure 2 replicas are in sync allways
    retention.ms: -1 # With this setting the data will never be deleted